defaultPlacement: end
fieldLayouts:
  24788bcc-ece8-4ed4-b4a9-4330ef55cd37:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-30T01:33:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: fdb72ffa-b710-4a5c-9dd7-090155fbdcc6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-31T02:49:46+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 2e7eeff7-13b1-4896-881c-eb60635f0b8a # Body
            handle: null
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e112c616-1478-4cca-a795-e37aeeb5f34f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ec1ec6d1-a6c6-4ae7-ab14-13c81d77c640
        userCondition: null
    thumbFieldKey: null
handle: category
name: Category
siteSettings:
  c06bf154-ba2d-40f9-9acc-9b0eb650ed25: # Gifts Around
    hasUrls: true
    template: category/_category.twig
    uriFormat: 'category/{slug}'
structure:
  maxLevels: null
  uid: 311f262d-d194-4371-a27b-721fa57982c1
