columnSuffix: null
handle: businessAddress
instructions: null
name: 'Business Address'
searchable: true
settings:
  maxAddresses: null
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
