columnSuffix: null
handle: optimizedImage
instructions: null
name: 'Optimized Image'
searchable: false
settings:
  displayDominantColorPalette: false
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  variants:
    -
      __assoc__:
        -
          - width
          - '576'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - jpg
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
