dateModified: 1769827786
email:
  fromEmail: info@giftsaround.com
  fromName: 'Gifts Around'
  replyToEmail: info@giftsaround.com
  template: ''
  transportSettings:
    host: smtp.zoho.com
    password: OwlLawn4200!
    port: '465'
    useAuthentication: '1'
    username: info@giftsaround.com
  transportType: craft\mail\transportadapters\Smtp
fs:
  uploads:
    hasUrls: true
    name: Uploads
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: '@web/uploads'
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    2e7eeff7-13b1-4896-881c-eb60635f0b8a: Body # Body
    5d23cabc-5a26-4e37-bca5-7f04116b4e8b: Simple # Simple
    6d3e1917-0432-4bae-96fe-6e467b048fb3: 'Contact ' # Contact 
    9d21a74f-c6b5-434c-8ed2-c75251a61c26: Business # Business
    19b7dc0c-1f0e-4d68-928d-0866f3bf5c99: 'Business Description' # Business Description
    21d5b2e7-055d-41a3-8842-86406bf86748: 'One Special (same each month)' # One Special (same each month)
    057bffe8-145d-4cf8-a820-52b631b73266: 'Optimized Image' # Optimized Image
    90c4ffa5-83bb-4af6-8837-6ad5bf1c323c: 'Business Phone' # Business Phone
    366a00bd-3f69-477a-8c1d-d922ec7aed18: 'Business Listing' # Business Listing
    0496e6ab-3bd6-4845-8754-3abae7832574: Business # Business
    937faf23-8b1b-469b-9235-401505a750f2: 'Business Address' # Business Address
    1681a684-620d-404c-a918-6af20caa8b8b: 'Business Email' # Business Email
    56699230-c9fb-4962-9d9b-36f4224b5a07: Business # Business
    abca8568-b497-484e-b4d3-5fe77d0d18dd: Category # Category
    b441d323-0b33-4f14-95c6-153d91a1674d: 'Business Website' # Business Website
    bb7cd503-f6ff-480a-b797-4ddb4f3ac9a3: 'Business Images' # Business Images
    c06bf154-ba2d-40f9-9acc-9b0eb650ed25: 'Gifts Around' # Gifts Around
    c7d677fc-5281-4cac-9550-ba58ae4ed0c7: Business # Business
    d4bb8a19-094e-48c4-b6ca-37154e3fc329: 'Monthly Specials' # Monthly Specials
    d12e90df-8855-47fa-8457-060d783e8a1d: 'Site Contact' # Site Contact
    f9b21139-b37c-4768-95ce-6a52e55e6352: Users # Users
    fc73028f-e956-417d-a9cb-27cf6b5d2777: Category # Category
    fce21e2d-42e7-4672-8d05-682879197a37: 'Nick Test' # Nick Test
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-clearcache:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  freeform:
    edition: pro
    enabled: true
    licenseKey: HL9340USSEDAJJUL2UUQS78V
    schemaVersion: 5.14.1
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: 1DO3AZKMYYVB6G4HYKTF92W7
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'Gifts Around'
  retryDuration: null
  schemaVersion: 5.9.0.8
  timeZone: America/New_York
