defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9d21a74f-c6b5-434c-8ed2-c75251a61c26 # Business
handle: businessListing
maxAuthors: 1
name: 'Business Listing'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c06bf154-ba2d-40f9-9acc-9b0eb650ed25: # Gifts Around
    enabledByDefault: true
    hasUrls: true
    template: business/index.twig
    uriFormat: business
type: single
